baseURL = "http://example.org/"
title = "Show me your Hugo version"
disableKinds = ["home", "section", "taxonomy", "taxonomyTerm", "RSS", "sitemap", "robotsTXT", "404"]

[outputFormats]
  [outputFormats.version-badge]
    baseName = "hugo-sitegen"
    mediaType = "image/svg+xml"

[params]
githubUrlPre = "https://api.github.com"
githubUrl = "/repos/gohugoio/hugo/releases/latest"
