name: Trigger Netlify Build
on:
  schedule:
    # Run every 30min
    - cron: "*/30 * * * *"
jobs:
  build:
    name: Request Netlify Webhook
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Curl request
        env:
          NETLIFY_BUILD_HOOK: ${{ secrets.NETLIFY_BUILD_HOOK }}
        run: |
          bash check-for-updates.sh || curl -X POST -d {} ${{ secrets.NETLIFY_BUILD_HOOK }}
